# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:16.10
    steps:
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  
  print_output_file:
    docker:
      - image: circleci/node:16.10
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

  # print_hello:
  #   docker:
  #     - image: circleci/node:16.10
  #   steps:
  #     - run: echo hello
  # print_world:
  #   docker:
  #     - image: circleci/node:16.10
  #   steps:
  #     - run: echo world
  # build:
  #   docker:
  #     - image: circleci/node:16.10
  #   steps:
  #     - run: echo $MY_ENV_VAR

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  # sample: # This is the name of the workflow, feel free to change it to better match your workflow.
  #   # Inside the workflow, you define the jobs you want to run.
  #   jobs:
  #     - print_hello
  #     - print_world:
  #         requires:
  #           - print_hello
      # - node/test:
      #     # This is the node version to use for the `cimg/node` tag
      #     # Relevant tags can be found on the CircleCI Developer Hub
      #     # https://circleci.com/developer/images/image/cimg/node
      #     version: '16.10'
      #     # If you are using yarn, change the line below from "npm" to "yarn"
      #     pkg-manager: npm
  # test_env_vars:
  #   jobs:
  #     - build
  # sharing files
  my_workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
        requires:
          - save_hello_world_output
